import {
    faCalculator,
    faFlask,
    faGlobe,
    faBook,
    faLaptopCode,
    faPalette,
    faComments,
    faPhoneAlt,
    faEnvelope,
    faShareAlt,
    faSearch,
    faSlidersH,
    faFilter,
    faSort,
    faChartPie,
    faTable,
    faDatabase,
    faFileAlt,
    faCamera,
    faQuestion,
} from '@fortawesome/free-solid-svg-icons';

export const iconsData = [
    { faIcon: faCalculator, isSelected: false },
    { faIcon: faFlask, isSelected: false },
    { faIcon: faGlobe, isSelected: false },
    { faIcon: faBook, isSelected: false },
    { faIcon: faLaptopCode, isSelected: false },
    { faIcon: faPalette, isSelected: false },
    { faIcon: faComments, isSelected: false },
    { faIcon: faPhoneAlt, isSelected: false },
    { faIcon: faEnvelope, isSelected: false },
    { faIcon: faShareAlt, isSelected: false },
    { faIcon: faSearch, isSelected: false },
    { faIcon: faSlidersH, isSelected: false },
    { faIcon: faFilter, isSelected: false },
    { faIcon: faSort, isSelected: false },
    { faIcon: faChartPie, isSelected: false },
    { faIcon: faTable, isSelected: false },
    { faIcon: faDatabase, isSelected: false },
    { faIcon: faFileAlt, isSelected: false },
    { faIcon: faCamera, isSelected: false },
    { faIcon: faQuestion, isSelected: false },
];
